//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class GameDineHubEntities : DbContext
    {
        public GameDineHubEntities()
            : base("name=GameDineHubEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<Lst_Gender> Lst_Gender { get; set; }
        public virtual DbSet<Lst_State> Lst_State { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserLoginHistory> UserLoginHistories { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<VotingResult> VotingResults { get; set; }
        public virtual DbSet<VotingRound> VotingRounds { get; set; }
        public virtual DbSet<TeamSong> TeamSongs { get; set; }
        public virtual DbSet<SiteProprity> SiteProprities { get; set; }
    }
}
