//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamSong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamSong()
        {
            this.VotingResults = new HashSet<VotingResult>();
        }
    
        public int ID { get; set; }
        public int fk_TeamID { get; set; }
        public string Name { get; set; }
        public string SongURL { get; set; }
        public Nullable<bool> VotingDone { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string SpotifySongUrl { get; set; }
    
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VotingResult> VotingResults { get; set; }
    }
}
