//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginHistory
    {
        public int ID { get; set; }
        public int fk_UserId { get; set; }
        public System.DateTime LoginDateTime { get; set; }
        public Nullable<System.DateTime> LogoutDateTime { get; set; }
        public string UserIP { get; set; }
        public string BrowserName { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
