//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.UserLoginHistories = new HashSet<UserLoginHistory>();
            this.UserRoles = new HashSet<UserRole>();
            this.SiteProprities = new HashSet<SiteProprity>();
        }
    
        public int ID { get; set; }
        public Nullable<int> fk_GenderID { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string PasswordRequestHash { get; set; }
        public Nullable<System.DateTime> PasswordRequestDate { get; set; }
        public int LoginAttempts { get; set; }
        public Nullable<System.DateTime> LastPasswordChange { get; set; }
        public string MobileNo { get; set; }
        public string PhoneNo { get; set; }
        public string PhoneExt { get; set; }
        public string Fax { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> IsNewsLetter { get; set; }
    
        public virtual Lst_Gender Lst_Gender { get; set; }
        public virtual Lst_State Lst_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLoginHistory> UserLoginHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteProprity> SiteProprities { get; set; }
    }
}
