//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotingResult
    {
        public int ID { get; set; }
        public int fk_VotingByTeamID { get; set; }
        public int fk_VotingToTeamID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int fk_TeamSongID { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual TeamSong TeamSong { get; set; }
    }
}
